name: Clone repositories

on:
  workflow_dispatch:

jobs:
  clone-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Clone or fetch group-data
        env:
          ACCESS_DATA: ${{ secrets.ACCESS_DATA }}
        run: git clone https://${{ secrets.ACCESS_DATA }}@github.com/kerzendorf-group/group-data.git

      - name: Configure git
        run: |
          touch kerzendorf-group.github.io/a.txt
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Clone my-other-repo"
          git push
