name: Clone repositories

on:
  workflow_dispatch:

jobs:
  clone:
    name: Clone
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clone repository
        run: |
          git clone git@github.com:kerzendorf-group/group-data.git
          git clone git@github.com:harshulgupt/groupwebsite_generator.git

      - name: List group-data
        run: |
          cd group-data
          ls -a

      - name: List groupwebsite_generator
        run: |
          cd groupwebsite_generator
          ls -a

      - name: Copy repository
        run: |
          cd group-data
          ls -a
          cp -r groupwebsite_data ../groupwebsite_generator/website-data/
          cp -r images ../groupwebsite_generator/website-data/
          cp -r members ../groupwebsite_generator/website-data/
          cp -r people ../groupwebsite_generator/website-data/
          cp -r research ../groupwebsite_generator/website-data/

      - name: Commit
        run: |
          cd groupwebsite_generator
          git add .
          git commit -m "Repo Files"
          git push
