name: Clone repositories

on:
  workflow_dispatch:

jobs:
  clone:
    name: Clone
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clone repository
        run: |
          git clone git@github.com:kerzendorf-group/group-data.git

      - name: Copy repository
        run: |
          cd group-data
          ls -a
          cp -r groupwebsite_data ../website-data/
          cp -r images ../website-data/
          cp -r members ../website-data/
          cp -r people ../website-data/
          cp -r research ../website-data/

          rm -rf .git .github .gitignore
          cd ..
          git add website-data
          git commit -m "Repo Files"
          git push
